# Generated by Django 5.1 on 2024-10-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Home.cart'),
            preserve_default=False,
        ),
    ]
