# Generated by Django 5.1 on 2024-10-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
