# Generated by Django 5.1.3 on 2024-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
