# Generated by Django 5.1.3 on 2024-11-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
